OBJS = \
ebasic.o \
db_compiler.o \
db_fun.o \
db_edit.o \
db_expr.o \
db_generate.o \
db_image.o \
db_scan.o \
db_statement.o \
db_symbols.o \
db_system.o \
db_vmint.o \
editbuf.o \
osint_posix.o

OBJS += db_vmdebug.o

#CFLAGS = -Wall -Os -DMAC -m32
CFLAGS = -Wall -DMAC -m32 -g
CFLAGS += -DLOAD_SAVE

%.o:	%.c
	cc $(CFLAGS) -c -o $@ $<

ebasic:	$(OBJS)
	cc $(CFLAGS) -o $@ $(OBJS)

run:	ebasic
	./ebasic

debug:	ebasic
	lldb ebasic

clean:
	rm -f *.o ebasic
